fix: Obtain domain name when mounting SMB
linuxdeepin/util-dfm pull request #76
Opened 2024-07-02 10:04 UTC by yang233000

Obtain domain name from configuration file

Log: Get workgroups under the specified configuration file

2024-07-02 10:07 UTC, itsXuSt approved these changes

2024-07-02 10:07 UTC, itsXuSt requested changes
拆成两个提交

2024-07-03 02:18 UTC, itsXuSt approved these changes

2024-07-03 02:28 UTC, max-lvs reviewed
no pms id!!!!!!

2024-07-10 03:06 UTC, max-lvs approved these changes

2024-07-10 03:16 UTC, max-lvs commented on src/dfm-mount/private/dnetworkmounter.cpp
> -                    info->insert(static_cast<char *>(k), static_cast<char *>(v));
no reson to fix here

2024-07-10 05:53 UTC, max-lvs approved these changes

2024-07-10 05:53 UTC, merged